import type { FinanceProps } from "@/types/finance";
import { addDays } from "date-fns";

export const MOCK_FINANCES: FinanceProps[] = [
  {
    budget: 5000,
    currency: "USD",
    endDate: addDays(new Date(), 10),
    id: "1",
    name: "Q1 Marketing Budget",
    remaining: 3000,
    spent: 2000,
    startDate: new Date(),
    status: "active",
  },
  {
    budget: 7500,
    currency: "EUR",
    endDate: addDays(new Date(), 20),
    id: "2",
    name: "Spring Ads",
    remaining: 4500,
    spent: 3000,
    startDate: addDays(new Date(), -5),
    status: "active",
  },
  {
    budget: 3000,
    currency: "USD",
    endDate: addDays(new Date(), 5),
    id: "3",
    name: "New Feature Development",
    remaining: 500,
    spent: 2500,
    startDate: addDays(new Date(), -10),
    status: "paused",
  },
  {
    budget: 10000,
    currency: "GBP",
    endDate: addDays(new Date(), 30),
    id: "4",
    name: "Annual Travel Budget",
    remaining: 8000,
    spent: 2000,
    startDate: new Date(),
    status: "active",
  },
  {
    budget: 2000,
    currency: "USD",
    endDate: addDays(new Date(), -1),
    id: "5",
    name: "Holiday Party Budget",
    remaining: 0,
    spent: 2000,
    startDate: addDays(new Date(), -15),
    status: "completed",
  },
];
